# Singular Value Decomposition

In [1]:
import torch
import numpy as np
_ = torch.manual_seed(0)

Generate a rank-deficient matrix W

In [ ]:
d, k = 10, 10

# This way we can generate a rank-deficient matrix
W_rank = 2
W = torch.randn(d,W_rank) @ torch.randn(W_rank,k) # 模拟一个全连接的权重w, 低秩矩阵, 秩为2
print(W)

tensor([[-1.0797,  0.5545,  0.8058, -0.7140, -0.1518,  1.0773,  2.3690,  0.8486,
         -1.1825, -3.2632],
        [-0.3303,  0.2283,  0.4145, -0.1924, -0.0215,  0.3276,  0.7926,  0.2233,
         -0.3422, -0.9614],
        [-0.5256,  0.9864,  2.4447, -0.0290,  0.2305,  0.5000,  1.9831, -0.0311,
         -0.3369, -1.1376],
        [ 0.7900, -1.1336, -2.6746,  0.1988, -0.1982, -0.7634, -2.5763, -0.1696,
          0.6227,  1.9294],
        [ 0.1258,  0.1458,  0.5090,  0.1768,  0.1071, -0.1327, -0.0323, -0.2294,
          0.2079,  0.5128],
        [ 0.7697,  0.0050,  0.5725,  0.6870,  0.2783, -0.7818, -1.2253, -0.8533,
          0.9765,  2.5786],
        [ 1.4157, -0.7814, -1.2121,  0.9120,  0.1760, -1.4108, -3.1692, -1.0791,
          1.5325,  4.2447],
        [-0.0119,  0.6050,  1.7245,  0.2584,  0.2528, -0.0086,  0.7198, -0.3620,
          0.1865,  0.3410],
        [ 1.0485, -0.6394, -1.0715,  0.6485,  0.1046, -1.0427, -2.4174, -0.7615,
          1.1147,  3.1054],
        [ 0.9088,  

Evaluate the rank of the matrix W

In [ ]:
W_rank = np.linalg.matrix_rank(W) # 计算矩阵的秩
print(f'Rank of W: {W_rank}')

Rank of W: 2


Calculate the SVD decomposition of the W matrix.

In [ ]:
# Perform SVD on W (W = UxSxV^T)
# 奇异值分解, S中大值对应的UV是原矩阵W中的主要特征向量
U, S, V = torch.svd(W) 
print(S)

# For rank-r factorization, keep only the first r singular values (and corresponding columns of U and V)
U_r = U[:, :W_rank]
S_r = torch.diag(S[:W_rank])
V_r = V[:, :W_rank].t()  # Transpose V_r to get the right dimensions

# Compute B = U_r * S_r and A = V_r
B = U_r @ S_r
A = V_r
print(f'Shape of B: {B.shape}')
print(f'Shape of A: {A.shape}')

tensor([1.1385e+01, 4.8439e+00, 3.4466e-07, 2.1101e-07, 1.2174e-07, 8.9196e-08,
        5.1100e-08, 3.9162e-08, 2.0093e-08, 1.3587e-08])
tensor([[ 0.1743,  0.0523,  0.0722, -0.1146, -0.0240, -0.1313, -0.2276, -0.0087,
         -0.1675, -0.1584],
        [ 0.0523,  0.0174,  0.0420, -0.0551, -0.0012, -0.0280, -0.0698,  0.0144,
         -0.0531, -0.0287],
        [ 0.0722,  0.0420,  0.2792, -0.3007,  0.0633,  0.0849, -0.1131,  0.2048,
         -0.1044,  0.1642],
        [-0.1146, -0.0551, -0.3007,  0.3327, -0.0586, -0.0551,  0.1689, -0.2060,
          0.1458, -0.1293],
        [-0.0240, -0.0012,  0.0633, -0.0586,  0.0248,  0.0590,  0.0258,  0.0624,
          0.0128,  0.0893],
        [-0.1313, -0.0280,  0.0849, -0.0551,  0.0590,  0.1768,  0.1609,  0.1230,
          0.1066,  0.2478],
        [-0.2276, -0.0698, -0.1131,  0.1689,  0.0258,  0.1609,  0.2986, -0.0045,
          0.2213,  0.1894],
        [-0.0087,  0.0144,  0.2048, -0.2060,  0.0624,  0.1230, -0.0045,  0.1746,
         -0.0210,  

Given the same input, check the output using the original W matrix and the matrices resulting from the decomposition.

In [ ]:
# 模拟一次全连接的计算
# Generate random bias and input
bias = torch.randn(d)
x = torch.randn(d)

# Compute y = Wx + bias
y = W @ x + bias # 原始权重计算的结果
# Compute y' = (B*A)x + bias
y_prime = (B @ A) @ x + bias # 使用低秩分解后的矩阵计算的结果

print("Original y using W:\n", y)
print("")
print("y' computed using BA:\n", y_prime)

Original y using W:
 tensor([ 7.2684e+00,  2.3162e+00,  7.7151e+00, -1.0446e+01, -8.1639e-03,
        -3.7270e+00, -1.1146e+01,  2.0207e+00, -9.6258e+00, -4.1163e+00])

y' computed using BA:
 tensor([ 7.2684e+00,  2.3162e+00,  7.7151e+00, -1.0446e+01, -8.1638e-03,
        -3.7270e+00, -1.1146e+01,  2.0207e+00, -9.6258e+00, -4.1163e+00])


In [36]:
print("Total parameters of W: ", W.nelement())
print("Total parameters of B and A: ", B.nelement() + A.nelement())

Total parameters of W:  100
Total parameters of B and A:  40
